.TH "Container< Type >" 3 "Tue May 10 2022" "PersonalCalendarOOP" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Container< Type >
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBContainer\fP (unsigned int cap)"
.br
.ti -1c
.RI "\fBContainer\fP (const \fBContainer\fP< Type > &container)"
.br
.ti -1c
.RI "void \fBadd\fP (const Type &element)"
.br
.ti -1c
.RI "void \fBswap\fP (Type &element1, Type &element2)"
.br
.ti -1c
.RI "unsigned int \fBgetIndex\fP (const Type &element)"
.br
.ti -1c
.RI "void \fBremove\fP (unsigned int index)"
.br
.ti -1c
.RI "unsigned int \fBgetSize\fP () const"
.br
.ti -1c
.RI "Type & \fBoperator[]\fP (unsigned index)"
.br
.ti -1c
.RI "\fBContainer\fP< Type > & \fBoperator=\fP (const \fBContainer\fP< Type > &other)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for PersonalCalendarOOP from the source code\&.
