.TH "Date" 3 "Tue May 10 2022" "PersonalCalendarOOP" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Date
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBDate\fP (unsigned int day, unsigned int month, unsigned int year)"
.br
.ti -1c
.RI "void \fBprint\fP (std::ostream &out=std::cout) const"
.br
.ti -1c
.RI "void \fBsetDay\fP (unsigned int day)"
.br
.ti -1c
.RI "void \fBsetMonth\fP (unsigned int month)"
.br
.ti -1c
.RI "void \fBsetYear\fP (unsigned int year)"
.br
.ti -1c
.RI "unsigned int \fBgetDay\fP () const"
.br
.ti -1c
.RI "unsigned int \fBgetMonth\fP () const"
.br
.ti -1c
.RI "unsigned int \fBgetYear\fP () const"
.br
.ti -1c
.RI "bool \fBoperator==\fP (const \fBDate\fP &date1) const"
.br
.ti -1c
.RI "\fBDate\fP & \fBoperator=\fP (const \fBDate\fP &other)"
.br
.ti -1c
.RI "bool \fBoperator<=\fP (const \fBDate\fP &date1) const"
.br
.ti -1c
.RI "bool \fBoperator>=\fP (const \fBDate\fP &date1) const"
.br
.ti -1c
.RI "\fBDate\fP & \fBoperator++\fP ()"
.br
.ti -1c
.RI "\fBDate\fP \fBoperator++\fP (int)"
.br
.ti -1c
.RI "void \fBprintDayOfWeek\fP (std::ostream &out=std::cout) const"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "std::istream & \fBoperator>>\fP (std::istream &in, \fBDate\fP &date)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for PersonalCalendarOOP from the source code\&.
