.TH "EventCalendar" 3 "Tue May 10 2022" "PersonalCalendarOOP" \" -*- nroff -*-
.ad l
.nh
.SH NAME
EventCalendar
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBEventCalendar\fP (const \fBEvent\fP *events, int numberEvents, int maxEvents)"
.br
.ti -1c
.RI "void \fBaddEvent\fP (const \fBEvent\fP &event)"
.br
.ti -1c
.RI "void \fBremoveEvent\fP (const \fBEvent\fP &event)"
.br
.ti -1c
.RI "void \fBsearchEvent\fP (\fBString\fP &string)"
.br
.ti -1c
.RI "void \fBchangeEvent\fP (const \fBEvent\fP &event)"
.br
.ti -1c
.RI "void \fBprintDayList\fP (const \fBDate\fP &date)"
.br
.ti -1c
.RI "void \fBoutputScheduleFromTo\fP (const \fBDate\fP &dateStart, const \fBDate\fP &dateEnd)"
.br
.ti -1c
.RI "void \fBfindFreeTime\fP (const \fBDate\fP &dateStart, const \fBDate\fP &dateEnd, const \fBTime\fP &startTime, const \fBTime\fP &endTime, int duration)"
.br
.ti -1c
.RI "void \fBsetEvents\fP (const \fBEvent\fP *events, int size, int maxSize=DEFAULT_CAP)"
.br
.ti -1c
.RI "void \fBwriteEvents\fP (const char *filename)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for PersonalCalendarOOP from the source code\&.
