.TH "Helper" 3 "Tue May 10 2022" "PersonalCalendarOOP" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Helper
.SH SYNOPSIS
.br
.PP
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static const char * \fBINVALID_DATE_MESSAGE\fP = 'The date you entered is invalid!'"
.br
.ti -1c
.RI "static const char * \fBDATE_INPUT_HELPER_MESSAGE\fP = 'Please enter a date in the correct format dd/mm/yyyy!'"
.br
.ti -1c
.RI "static const char \fBDATE_SEPARATOR\fP = '/'"
.br
.ti -1c
.RI "static const char * \fBDATE_NOT_FREE_ERROR_MESSAGE\fP = 'The event cannot be added because an event with the same date exists!'"
.br
.ti -1c
.RI "static const char \fBTIME_SEPARATOR\fP = ':'"
.br
.ti -1c
.RI "static const char * \fBTIME_INPUT_HELPER_MESSAGE\fP = 'Please enter the hours in the following format: hh:ii'"
.br
.ti -1c
.RI "static const char * \fBINVALID_TIME_ERROR_MESSAGE\fP = 'The entered time is invalid!'"
.br
.ti -1c
.RI "static const char * \fBEVENT_NOT_FOUND_ERROR\fP = 'Event with this information was not found!'"
.br
.ti -1c
.RI "static const char * \fBEVENT_FOUND_MESSAGE\fP = 'Event with this information was found!'"
.br
.ti -1c
.RI "static const char * \fBHELPER_MESSAGE_CHANGE_EVENT\fP"
.br
.ti -1c
.RI "static const char * \fBUNKNOWN_COMMAND_USED\fP = 'Unknown command was used!'"
.br
.ti -1c
.RI "static const char * \fBMAX_CAPACITY_REACHED_ERROR\fP = 'Max capacity reached!'"
.br
.ti -1c
.RI "static const int \fBERROR_INDEX\fP = \-1"
.br
.ti -1c
.RI "static const char * \fBNAME_INPUT_HELPER_MESSAGE\fP = 'Please enter the name of the event:'"
.br
.ti -1c
.RI "static const char * \fBCOMMENT_INPUT_HELPER_MESSAGE\fP = 'Please enter the comment of the event:'"
.br
.ti -1c
.RI "static const char * \fBCOMMANDS_HELPER_MESSAGE\fP"
.br
.ti -1c
.RI "static const char * \fBENTER_COMMAND_MESSAGE\fP = 'Enter command:\\n'"
.br
.ti -1c
.RI "static const char * \fBEXIT_MESSAGE\fP"
.br
.ti -1c
.RI "static const char * \fBSAVED_WORKLOAD\fP = 'Your workload was successfully saved to a file: '"
.br
.ti -1c
.RI "static const char * \fBENTER_STRING\fP = 'Enter string to search for!'"
.br
.ti -1c
.RI "static const unsigned int \fBMONTH_DIFFERENCE_CONST\fP = 2"
.br
.ti -1c
.RI "static const char * \fBDATE_FREE\fP = ' FREE'"
.br
.ti -1c
.RI "static const char * \fBDATE_BUSY\fP = ' BUSY'"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "const char * Helper::COMMANDS_HELPER_MESSAGE\fC [static]\fP"
\fBInitial value:\fP
.PP
.nf
= "Hello! \n"
                                               "To add an event write: make \n"
                                               "To remove an event write: cancel \n"
                                               "To change information about an event write: change \n"
                                               "To search an event write: search \n"
                                               "To show your schedule for a certain date write: show:day \n"
                                               "To find free time in a certain week write: free \n"
                                               "To see your daily schedule for a certain week write: show:busy \n"
                                               "To exit the program write: exit \n"
.fi
.SS "const char * Helper::EXIT_MESSAGE\fC [static]\fP"
\fBInitial value:\fP
.PP
.nf
= "Goodbye! \n"
                                           "Your event calendar is currently being saved to: "
.fi
.SS "const char * Helper::HELPER_MESSAGE_CHANGE_EVENT\fC [static]\fP"
\fBInitial value:\fP
.PP
.nf
= "Hello! In order to change information for the event build the string: "
                                                  "\n To change the date: write 'd'"
                                                  "\n To change the name: write 'n'"
                                                  "\n To change the comment: write 'c'"
                                                  "\n Your final string could look like that dnc"
.fi


.SH "Author"
.PP 
Generated automatically by Doxygen for PersonalCalendarOOP from the source code\&.
