.TH "Program" 3 "Tue May 10 2022" "PersonalCalendarOOP" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Program
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBrun\fP ()"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for PersonalCalendarOOP from the source code\&.
